{"name":"Runs Cucumber Feature","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"java.lang.AssertionError: Exception caught while entering the value in :Username field, message is->null","trace":"cucumber.runtime.CucumberException: java.lang.AssertionError: Exception caught while entering the value in :Username field, message is->null\r\n\tat cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)\r\n\tat cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)\r\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:583)\r\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)\r\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:648)\r\n\tat org.testng.TestRunner.run(TestRunner.java:505)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:455)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:364)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1137)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1049)\r\n\tat org.testng.TestNG.run(TestNG.java:1017)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\r\nCaused by: java.lang.AssertionError: Exception caught while entering the value in :Username field, message is->null\r\n\tat org.testng.Assert.fail(Assert.java:96)\r\n\tat appmanager.ExtentCucumberFormatter.testStepFailed(ExtentCucumberFormatter.java:252)\r\n\tat appmanager.HelperBase.enterText(HelperBase.java:1391)\r\n\tat appmanager.HelperBase.login(HelperBase.java:214)\r\n\tat tests.SonarqubeStepDefs.user_logs_into_the_application(SonarqubeStepDefs.java:22)\r\n\tat âœ½.Given user logs into the application:\"sqetst01\"(features/Testing.feature:5)\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"arg0","value":"testing"}],"start":1693233724492,"stop":1693233763338,"uuid":"76c9120e-0f7e-4e0e-80ac-898d1bbace37","historyId":"f3cabd556fc2f6a221c38f54845ab935","fullName":"cucumber.api.testng.AbstractTestNGCucumberTests.feature","labels":[{"name":"package","value":"tests.TestRunner"},{"name":"testClass","value":"tests.TestRunner"},{"name":"testMethod","value":"feature"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"SQE_Selenium_TestingProject"},{"name":"subSuite","value":"tests.TestRunner"},{"name":"host","value":"ws-qatools-p2"},{"name":"thread","value":"74584@ws-qatools-p2.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[]}